### PR TITLE
Minor Fixes and Comments

### PR DESCRIPTION
**Pull request by BSGreaves**
## DESCRIPTION
Added and standardized comments in all the models, making them more specific.
Added "Name" field to the TrainingProgram model and updated the DBInitializer to reflect that change in our seed data.
Removed "Required" from dates in the Customer Model.

## STEPS TO TEST
1. Clone this branch to a local repo
2. In terminal, run `dotnet ef migrations add {migrationName}`, `dotnet ef database update`, `dotnet build` then `dotnet run`
3. Test functionality
* Check that seed data in the database contains the Name field in the TrainingProgram table
* Check over all the comments in the Models for omissions or errors.
## REFERENCE

[ERD](https://github.com/Phat-Taupe-Pests/Bangazon)

### CODE REVIEW

**Comment by augsismyburger** [comment]
Tests Passed. 👍

**Comment by arock83** [comment]
Tests Pass 👍

**Comment by arock83** [comment]
👍

**Comment by augsismyburger** [comment]
Still good 👍

**Pull request merged**
