### PR TITLE
Eliza template

### PR DESCRIPTION
**Pull request by elizawmeeks**
***********

DESCRIPTION
	Put together the file structure, including context, Startup.cs. Wrote Customer Model and Controller, migrated then, and got them to put/post/getAll/getSingle.

STEPS TO TEST
        0. Set up environment variable. Mine looks like this, edit for your system (use pwd to find the path in your directory): 

export BANGAZON_DB="/path/to/repo/BangazonAPI/bangazonapi.db"

        0.5. Database file should be named bangazonapi.db
	1. Clone this branch to a local repo
	2. In terminal, run ```dotnet build``` then ```dotnet run```
	3. Test functionality
		A. Use POSTMAN to post, put, getSingle and getAll customers.
		B. POST url is http://localhost:5000/Customer
		C. PUT url is http://localhost:5000/Customer/{id}
                D. GET single url is http://localhost:5000/Customer/{id}
                E. GET all url is http://localhost:5000/Customer

REFERENCE
	[Ticket](https://github.com/Phat-Taupe-Pests/BangazonAPI/issues/1)
	[ERD](https://github.com/Phat-Taupe-Pests/Bangazon)
	
***********

### CODE REVIEW

**Comment by chazhenricks** [comment]
Maybe make a note to source ~/.zshrc (or wherever you store your path) and run 
`dotnet ef database update` before an actual .db file will be created and usable

**Comment by chazhenricks** [comment]
GET/PUT/POST are working correctly on my machine after running `source ~/.zshrc` and `dotnet ef database update` _before_ `dotnet run`

**Comment by augsismyburger** [comment]
All Tests Passed, after adding path and `dotnet ef database update` before `dotnet run`

**Comment by elizawmeeks** [comment]
When using POSTMAN make sure to set the header key as "Content-type" and the value as "application/json"

**Comment by BSGreaves** [comment]
All verbs working correctly

**Pull request merged**
