### PR TITLE
Chaz employee comments

### PR DESCRIPTION
**Pull request by chazhenricks**
## DESCRIPTION
Added additional documentation to Models/Employee.cs and Controllers/EmployeeController.cs

## STEPS TO TEST
1. Clone this branch to a local repo
2. In terminal, run `dotnet ef migrations add {migrationName}`, `dotnet ef database update`, `dotnet build` then `dotnet run`

## REFERENCE

[Ticket](https://github.com/Phat-Taupe-Pests/BangazonAPI/issues/6)

[ERD](https://github.com/Phat-Taupe-Pests/Bangazon)

### CODE REVIEW

**Review by elizawmeeks — COMMENTED** [review]
Looks good 👍

**Review by elizawmeeks — COMMENTED** [review]
👍

**Comment by augsismyburger** [comment]
Good Good.

**Comment by arock83** [comment]
🥇

**Pull request merged**
