### PR TITLE
read this

### PR DESCRIPTION
**Pull request by arock83**
## DESCRIPTION
Added installing core dependencies and note to when datetimes are autogenerated

## STEPS TO TEST
1. Clone this branch to a local repo
2. In terminal, run `dotnet ef migrations add {migrationName}`, `dotnet ef database update`, `dotnet build` then `dotnet run`
3. Read the ReadMe

## REFERENCE

No Ticket

[ERD](https://github.com/Phat-Taupe-Pests/Bangazon)

### CODE REVIEW

**Comment by augsismyburger** [comment]
Sooo Readable. 👍

**Review by elizawmeeks — COMMENTED** [review]
10/5

**Comment by chazhenricks** [comment]
I did, in fact, read this.

**Comment by chazhenricks** [comment]
5/7

**Pull request merged**
