### PR TITLE
Added Computer Model and Controller

### PR DESCRIPTION
**Pull request by augsismyburger**
## DESCRIPTION
Added Computer Model and Controller.
Should be able to Get(single or all), Post, Put, and Delete

## STEPS TO TEST
1. Clone this branch to a local repo
2. In terminal, run `dotnet ef migrations add {migrationName}`, `dotnet ef database update`, `dotnet build` then `dotnet run`
3. Test functionality

A. Method Post Paste: http://localhost:5000/Computer into url section on Postman. Paste `{"DatePurchased": "01-18-1988"}` into the body section. Send request.
Should return:
`{
    "computerID": 1,
    "datePurchased": "1988-01-18T00:00:00",
    "dateDecomissioned": "0001-01-01T00:00:00"
}`
B. Method Get(all) Paste: http://localhost:5000/Computer into url section on Postman. Send request.
Should return:
`{
    "computerID": 1,
    "datePurchased": "1988-01-18T00:00:00",
    "dateDecomissioned": "0001-01-01T00:00:00"
}`
C. Method Get(specific id) Paste: http://localhost:5000/Computer/1 into url section on Postman. Send request.
Should return:
`{
    "computerID": 1,
    "datePurchased": "1988-01-18T00:00:00",
    "dateDecomissioned": "0001-01-01T00:00:00"
}`
D. Method Put Paste: http://localhost:5000/Computer/1 into url section on Postman. Paste 
`{
    "computerID": 1,
    "datePurchased": "2000-01-18T00:00:00",
    "dateDecomissioned": "0001-01-01T00:00:00"
}`
into the body section. Send request.
Should return:
`204 No Content`
E. Method Delete Paste: http://localhost:5000/Computer/1 into url section on Postman. Send Request.
Should Return:
`{
    "computerID": 1,
    "datePurchased": "2000-01-18T00:00:00",
    "dateDecomissioned": "0001-01-01T00:00:00"
}`

## REFERENCE

[Ticket 8](https://github.com/Phat-Taupe-Pests/BangazonAPI/issues/8)

[ERD](https://github.com/Phat-Taupe-Pests/Bangazon)

### CODE REVIEW

**Comment by elizawmeeks** [comment]
Looks good, everything works.

**Comment by BSGreaves** [comment]
All methods tested and working. Good pull request 👍

**Comment by arock83** [comment]
All Tests Work 👍

**Comment by chazhenricks** [comment]
COOL

**Pull request merged**
